### PR TITLE
Add metadata for postboxes

### PR DESCRIPTION
**Pull request by FloEdelmann**
Follow-up to and extracted from #6, see https://github.com/streetcomplete/StreetComplete/discussions/4096#discussioncomment-2940702.

Note that I included two more files in the second commit, those may be too subjective to include.

### CODE REVIEW

**Review by westnordost — CHANGES_REQUESTED** [review]
"addressHasStreet" sounds a bit weird. The thing with Japan is that many (city) **roads** do not have a name, hence, addresses do usually not work with street+housenumber but using a different system. So it is less about addresses but about roads. IMO this file should be deleted, as it basically just got one entry.

Please rename postBoxes -> postboxes ("postbox" is one word in English)

Fire hydrant diameter signs: The comment contains "usually". This is too fuzzy. Is this about whether there are hydrant diameter signs at all, or whether there are "usually" ones? If the latter, it should not be included. If the former, it can be included but the comment needs to be changed.

Bus stop identifiers: IMO this is again a too fuzzy information to include. (Comment also mentions "usually").

Regarding "summit markings", I think it should be removed. Whether or such things are common very much depends on the (climbing) community, it is not result of any legislation or regulation. I.e., that file could be named "someSummitsMayHaveSummitMarkings".

**Comment by FloEdelmann** [comment]
> "addressHasStreet" […] should be deleted, as it basically just got one entry.

Alright.

> "postbox" is one word in English

I trusted Android Studio's spell checking which complained about it :slightly_frowning_face: 
It actually is a British term: https://dict.leo.org/englisch-deutsch/postbox
I'll change it.

> Fire hydrant diameter signs: […] Is this about whether there are hydrant diameter signs at all, or whether there are "usually" ones?

It should be the former, but I guess it'd be more useful to differentiate between "sign is mandatory (by law)", "sign exists but is optional" and "sign does not exist / unknown". But that'd require more research, so let's leave it out for now.

> Bus stop identifiers: IMO this is again a too fuzzy information to include.

I think it should be quite subjective, but let's leave it out too.

> Regarding "summit markings", I think it should be removed.

Okay.

**Comment by westnordost** [comment]
> It should be the former, but I guess it'd be more useful to differentiate between "sign is mandatory (by law)", "sign exists but is optional" and "sign does not exist / unknown". But that'd require more research, so let's leave it out for now.

Of these, only "sign does exist / no sign exists" is realistic, I'd say.

**Review by westnordost — APPROVED** [review]

**Comment by matkoniecz** [comment]
Is there any remaining blocker here?

**Pull request merged**
